import { Application, MemberWithRole, Role } from "@/lib/types";

export const demoRoles: Role[] = [
  {
    id: "role-leader",
    name: "Лидер",
    slug: "leader",
    description: "Главный хранитель гильдии и её решений.",
    color_theme: "royal-gold",
    sort_order: 1
  },
  {
    id: "role-chat-manager",
    name: "Управляющий чатом",
    slug: "chat-manager",
    description: "Следит за порядком, общением и атмосферой в чате.",
    color_theme: "graphite-gold",
    sort_order: 2
  },
  {
    id: "role-chat-manager-female",
    name: "Управляющая чатом",
    slug: "chat-manager-female",
    description: "Помогает участникам и держит чат в спокойном порядке.",
    color_theme: "amber-gold",
    sort_order: 3
  },
  {
    id: "role-deputy",
    name: "Временный лидер (заместитель)",
    slug: "deputy",
    description: "Берёт руководство на себя, когда это нужно гильдии.",
    color_theme: "deep-blue-gold",
    sort_order: 4
  },
  {
    id: "role-officer-i",
    name: "Офицер I",
    slug: "officer-i",
    description: "Старший офицер состава.",
    color_theme: "dark-bronze",
    sort_order: 5
  },
  {
    id: "role-officer-ii",
    name: "Офицер II",
    slug: "officer-ii",
    description: "Офицер боевого состава.",
    color_theme: "dark-copper",
    sort_order: 6
  },
  {
    id: "role-officer-iii",
    name: "Офицер III",
    slug: "officer-iii",
    description: "Офицер поддержки состава.",
    color_theme: "dark-silver",
    sort_order: 7
  },
  {
    id: "role-advisor-i",
    name: "Советник I",
    slug: "advisor-i",
    description: "Помогает советами, наблюдением и опытом.",
    color_theme: "dark-emerald",
    sort_order: 8
  },
  {
    id: "role-checker-i",
    name: "Проверяющий I",
    slug: "checker-i",
    description: "Проверяет анкеты и новых кандидатов.",
    color_theme: "dark-blue",
    sort_order: 9
  },
  {
    id: "role-checker-ii",
    name: "Проверяющий II",
    slug: "checker-ii",
    description: "Помогает проверять заявки и данные участников.",
    color_theme: "dark-violet",
    sort_order: 10
  },
  {
    id: "role-member",
    name: "Участник",
    slug: "member",
    description: "Основной состав гильдии.",
    color_theme: "dark-gray",
    sort_order: 11
  },
  {
    id: "role-rookie",
    name: "Новичок",
    slug: "rookie",
    description: "Новый участник на этапе знакомства с гильдией.",
    color_theme: "graphite",
    sort_order: 12
  }
];

const roleBySlug = (slug: string) => demoRoles.find((role) => role.slug === slug) ?? demoRoles[10];

export const demoMembers: MemberWithRole[] = [
  {
    id: "demo-leader",
    name: "Амир",
    age: 20,
    birth_date: "2006-02-14",
    game_nickname: "KNTL.Crown",
    game_id: "123456789",
    invited_by: "Основатель",
    nationality: "Казах",
    languages: "Русский, Казахский",
    location: "Алматы",
    device: "iPhone",
    ult_skill: "Сильный",
    sns_skill: "Сильный",
    first_impression: "Гильдия должна быть дисциплиной, уважением и честной игрой.",
    photo_url: "/avatars/leader.svg",
    role_id: "role-leader",
    status: "active",
    joined_at: "2025-01-12",
    role: roleBySlug("leader")
  },
  {
    id: "demo-chat",
    name: "Данил",
    age: 18,
    birth_date: "2007-04-08",
    game_nickname: "KNTL.Chat",
    game_id: "771255018",
    invited_by: "Лидер",
    nationality: "Русский",
    languages: "Русский",
    location: "Астана",
    device: "Android",
    ult_skill: "Хороший",
    sns_skill: "Средний",
    first_impression: "Сразу понравился спокойный порядок в составе.",
    photo_url: "/avatars/chat.svg",
    role_id: "role-chat-manager",
    status: "active",
    joined_at: "2025-03-04",
    role: roleBySlug("chat-manager")
  },
  {
    id: "demo-officer",
    name: "Рамиль",
    age: 19,
    birth_date: "2006-09-20",
    game_nickname: "KNTL.Shield",
    game_id: "845620113",
    invited_by: "Офицер I",
    nationality: "Татарин",
    languages: "Русский, Татарский",
    location: "Казань",
    device: "Android",
    ult_skill: "Сильный",
    sns_skill: "Хороший",
    first_impression: "Здесь ценят стабильность и командную игру.",
    photo_url: "/avatars/officer.svg",
    role_id: "role-officer-i",
    status: "active",
    joined_at: "2025-05-18",
    role: roleBySlug("officer-i")
  },
  {
    id: "demo-advisor",
    name: "София",
    age: 21,
    birth_date: "2004-11-03",
    game_nickname: "KNTL.Archive",
    game_id: "924681002",
    invited_by: "Совет",
    nationality: "Казашка",
    languages: "Русский, Казахский, Английский",
    location: "Шымкент",
    device: "iPad",
    ult_skill: "Хороший",
    sns_skill: "Хороший",
    first_impression: "Портал ощущается как место, где у каждого есть история.",
    photo_url: "/avatars/advisor.svg",
    role_id: "role-advisor-i",
    status: "active",
    joined_at: "2025-07-02",
    role: roleBySlug("advisor-i")
  },
  {
    id: "demo-checker",
    name: "Нурсултан",
    age: 17,
    birth_date: "2008-01-27",
    game_nickname: "KNTL.Check",
    game_id: "665501442",
    invited_by: "Управляющий чатом",
    nationality: "Казах",
    languages: "Русский, Казахский",
    location: "Караганда",
    device: "Android",
    ult_skill: "Средний",
    sns_skill: "Хороший",
    first_impression: "Понравилось, что анкеты проверяют аккуратно.",
    photo_url: "/avatars/checker.svg",
    role_id: "role-checker-i",
    status: "active",
    joined_at: "2025-08-19",
    role: roleBySlug("checker-i")
  },
  {
    id: "demo-member",
    name: "Алина",
    age: 16,
    birth_date: "2009-06-30",
    game_nickname: "KNTL.Astra",
    game_id: "550913728",
    invited_by: "Подруга",
    nationality: "Казашка",
    languages: "Русский",
    location: "Павлодар",
    device: "iPhone",
    ult_skill: "Хороший",
    sns_skill: "Средний",
    first_impression: "Красиво, спокойно, без лишнего шума.",
    photo_url: "/avatars/member.svg",
    role_id: "role-member",
    status: "active",
    joined_at: "2025-09-01",
    role: roleBySlug("member")
  },
  {
    id: "demo-rookie",
    name: "Максим",
    age: 15,
    birth_date: "2010-03-11",
    game_nickname: "KNTL.New",
    game_id: "739002611",
    invited_by: "Telegram",
    nationality: "Русский",
    languages: "Русский",
    location: "Омск",
    device: "Android",
    ult_skill: "Учусь",
    sns_skill: "Средний",
    first_impression: "Хочется стать частью сильного состава.",
    photo_url: "/avatars/rookie.svg",
    role_id: "role-rookie",
    status: "active",
    joined_at: "2025-10-10",
    role: roleBySlug("rookie")
  },
  {
    id: "demo-archived",
    name: "Егор",
    age: 18,
    birth_date: "2007-12-05",
    game_nickname: "KNTL.Old",
    game_id: "480016622",
    invited_by: "Старый состав",
    nationality: "Русский",
    languages: "Русский",
    location: "Новосибирск",
    device: "Android",
    ult_skill: "Средний",
    sns_skill: "Средний",
    first_impression: "Был частью первого набора участников.",
    photo_url: "/avatars/archive.svg",
    role_id: "role-member",
    status: "archived",
    joined_at: "2024-12-20",
    role: roleBySlug("member")
  }
];

export const demoApplications: Application[] = [
  {
    id: "demo-application",
    name: "Тимур",
    age: 16,
    birth_date: "2009-02-02",
    game_nickname: "Pending.K",
    game_id: "900221144",
    invited_by: "Telegram",
    nationality: "Казах",
    languages: "Русский, Казахский",
    location: "Тараз",
    device: "Android",
    ult_skill: "Хороший",
    sns_skill: "Учусь",
    first_impression: "Гильдия выглядит серьёзной и собранной.",
    photo_url: null,
    status: "pending"
  }
];
